import './globals.css';

import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import { Provider as ReactWrapBalancerProvider } from 'react-wrap-balancer';

import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: ['italic', 'italic'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(lato.className, 'bg-slate-50')}
        suppressHydrationWarning={true}
      >
        <main className="mx-auto max-w-[1400px]">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
          >
            <ReactWrapBalancerProvider>
              {children}
              <Toaster />
            </ReactWrapBalancerProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
