import './globals.css';

import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import { Provider as ReactWrapBalancerProvider } from 'react-wrap-balancer';

import CategoriesMenu from '@/components/pages/categories-menu';
import SearchBar from '@/components/pages/search-bar';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  style: ['italic', 'italic'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(lato.className, 'bg-slate-50')}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <ReactWrapBalancerProvider>
            <div className="mx-auto max-w-[1400px]">
              <SearchBar className="my-5" />
              <CategoriesMenu />
              {children}
              <Toaster />
            </div>
          </ReactWrapBalancerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
